// SPDX-License-Identifier: UNLICENSED
// !! THIS FILE WAS AUTOGENERATED BY abi-to-sol v0.5.2. SEE SOURCE BELOW. !!
pragma solidity >=0.7.0 <0.9.0;

interface IRarityCodexCommonTools {
    function artisans_tools()
        external
        pure
        returns (
            uint8 id,
            uint256 cost,
            uint256 weight,
            string memory name,
            string memory description,
            int8[36] memory skill_bonus
        );

    function base_type() external view returns (uint8);

    function class() external view returns (string memory);

    function index() external view returns (string memory);

    function item_by_id(uint256 _id)
        external
        pure
        returns (
            uint8 id,
            uint256 cost,
            uint256 weight,
            string memory name,
            string memory description,
            int8[36] memory skill_bonus
        );
}

// THIS FILE WAS AUTOGENERATED FROM THE FOLLOWING ABI JSON:
/*
[{"inputs":[],"name":"artisans_tools","outputs":[{"internalType":"uint8","name":"id","type":"uint8"},{"internalType":"uint256","name":"cost","type":"uint256"},{"internalType":"uint256","name":"weight","type":"uint256"},{"internalType":"string","name":"name","type":"string"},{"internalType":"string","name":"description","type":"string"},{"internalType":"int8[36]","name":"skill_bonus","type":"int8[36]"}],"stateMutability":"pure","type":"function"},{"inputs":[],"name":"base_type","outputs":[{"internalType":"uint8","name":"","type":"uint8"}],"stateMutability":"view","type":"function"},{"inputs":[],"name":"class","outputs":[{"internalType":"string","name":"","type":"string"}],"stateMutability":"view","type":"function"},{"inputs":[],"name":"index","outputs":[{"internalType":"string","name":"","type":"string"}],"stateMutability":"view","type":"function"},{"inputs":[{"internalType":"uint256","name":"_id","type":"uint256"}],"name":"item_by_id","outputs":[{"internalType":"uint8","name":"id","type":"uint8"},{"internalType":"uint256","name":"cost","type":"uint256"},{"internalType":"uint256","name":"weight","type":"uint256"},{"internalType":"string","name":"name","type":"string"},{"internalType":"string","name":"description","type":"string"},{"internalType":"int8[36]","name":"skill_bonus","type":"int8[36]"}],"stateMutability":"pure","type":"function"}]
*/
