// SPDX-License-Identifier: UNLICENSED
// !! THIS FILE WAS AUTOGENERATED BY abi-to-sol v0.5.2. SEE SOURCE BELOW. !!
pragma solidity >=0.7.0 <0.9.0;
pragma experimental ABIEncoderV2;

interface IRarityCodexMasterworkWeapons {
    function class() external view returns (string memory);

    function get_damage_type_by_id(uint256 _id)
        external
        pure
        returns (string memory description);

    function get_encumbrance_by_id(uint256 _id)
        external
        pure
        returns (string memory description);

    function get_proficiency_by_id(uint256 _id)
        external
        pure
        returns (string memory description);

    function index() external view returns (string memory);

    function item_by_id(uint256 _id)
        external
        pure
        returns (Weapon memory weapon);
}

struct Weapon {
    uint256 id;
    uint256 cost;
    uint256 proficiency;
    uint256 encumbrance;
    uint256 damage_type;
    uint256 weight;
    uint256 damage;
    uint256 critical;
    int256 critical_modifier;
    uint256 range_increment;
    string name;
    string description;
}

// THIS FILE WAS AUTOGENERATED FROM THE FOLLOWING ABI JSON:
/*
[{"inputs":[],"name":"class","outputs":[{"internalType":"string","name":"","type":"string"}],"stateMutability":"view","type":"function"},{"inputs":[{"internalType":"uint256","name":"_id","type":"uint256"}],"name":"get_damage_type_by_id","outputs":[{"internalType":"string","name":"description","type":"string"}],"stateMutability":"pure","type":"function"},{"inputs":[{"internalType":"uint256","name":"_id","type":"uint256"}],"name":"get_encumbrance_by_id","outputs":[{"internalType":"string","name":"description","type":"string"}],"stateMutability":"pure","type":"function"},{"inputs":[{"internalType":"uint256","name":"_id","type":"uint256"}],"name":"get_proficiency_by_id","outputs":[{"internalType":"string","name":"description","type":"string"}],"stateMutability":"pure","type":"function"},{"inputs":[],"name":"index","outputs":[{"internalType":"string","name":"","type":"string"}],"stateMutability":"view","type":"function"},{"inputs":[{"internalType":"uint256","name":"_id","type":"uint256"}],"name":"item_by_id","outputs":[{"components":[{"internalType":"uint256","name":"id","type":"uint256"},{"internalType":"uint256","name":"cost","type":"uint256"},{"internalType":"uint256","name":"proficiency","type":"uint256"},{"internalType":"uint256","name":"encumbrance","type":"uint256"},{"internalType":"uint256","name":"damage_type","type":"uint256"},{"internalType":"uint256","name":"weight","type":"uint256"},{"internalType":"uint256","name":"damage","type":"uint256"},{"internalType":"uint256","name":"critical","type":"uint256"},{"internalType":"int256","name":"critical_modifier","type":"int256"},{"internalType":"uint256","name":"range_increment","type":"uint256"},{"internalType":"string","name":"name","type":"string"},{"internalType":"string","name":"description","type":"string"}],"internalType":"struct Weapon","name":"weapon","type":"tuple"}],"stateMutability":"pure","type":"function"}]
*/
